//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tail.Views.Templates {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Tail.Views.Templates.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string OKText {
            get {
                return ResourceManager.GetString("OKText", resourceCulture);
            }
        }
        
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        internal static string SubmitText {
            get {
                return ResourceManager.GetString("SubmitText", resourceCulture);
            }
        }
        
        internal static string ContinueText {
            get {
                return ResourceManager.GetString("ContinueText", resourceCulture);
            }
        }
        
        internal static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
        
        internal static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        internal static string FreeText {
            get {
                return ResourceManager.GetString("FreeText", resourceCulture);
            }
        }
        
        internal static string PaidText {
            get {
                return ResourceManager.GetString("PaidText", resourceCulture);
            }
        }
        
        internal static string MoneyLineText {
            get {
                return ResourceManager.GetString("MoneyLineText", resourceCulture);
            }
        }
        
        internal static string SpreadText {
            get {
                return ResourceManager.GetString("SpreadText", resourceCulture);
            }
        }
        
        internal static string OverUnderText {
            get {
                return ResourceManager.GetString("OverUnderText", resourceCulture);
            }
        }
        
        internal static string PurchasedText {
            get {
                return ResourceManager.GetString("PurchasedText", resourceCulture);
            }
        }
        
        internal static string FacebookText {
            get {
                return ResourceManager.GetString("FacebookText", resourceCulture);
            }
        }
        
        internal static string AppleText {
            get {
                return ResourceManager.GetString("AppleText", resourceCulture);
            }
        }
        
        internal static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        internal static string ForgotPasswordText {
            get {
                return ResourceManager.GetString("ForgotPasswordText", resourceCulture);
            }
        }
        
        internal static string RememberMeText {
            get {
                return ResourceManager.GetString("RememberMeText", resourceCulture);
            }
        }
        
        internal static string DontHaveAccountText {
            get {
                return ResourceManager.GetString("DontHaveAccountText", resourceCulture);
            }
        }
        
        internal static string SignUpText {
            get {
                return ResourceManager.GetString("SignUpText", resourceCulture);
            }
        }
        
        internal static string OrText {
            get {
                return ResourceManager.GetString("OrText", resourceCulture);
            }
        }
        
        internal static string SkipText {
            get {
                return ResourceManager.GetString("SkipText", resourceCulture);
            }
        }
        
        internal static string FacebookSignUpText {
            get {
                return ResourceManager.GetString("FacebookSignUpText", resourceCulture);
            }
        }
        
        internal static string AppleSignUpText {
            get {
                return ResourceManager.GetString("AppleSignUpText", resourceCulture);
            }
        }
        
        internal static string SignUpTitleText {
            get {
                return ResourceManager.GetString("SignUpTitleText", resourceCulture);
            }
        }
        
        internal static string EmailSignUpText {
            get {
                return ResourceManager.GetString("EmailSignUpText", resourceCulture);
            }
        }
        
        internal static string AlreadyHaveAccountText {
            get {
                return ResourceManager.GetString("AlreadyHaveAccountText", resourceCulture);
            }
        }
        
        internal static string CreateAccountText {
            get {
                return ResourceManager.GetString("CreateAccountText", resourceCulture);
            }
        }
        
        internal static string CreateAccountButtonText {
            get {
                return ResourceManager.GetString("CreateAccountButtonText", resourceCulture);
            }
        }
        
        internal static string PlaceHolderName {
            get {
                return ResourceManager.GetString("PlaceHolderName", resourceCulture);
            }
        }
        
        internal static string PlaceHolderEmail {
            get {
                return ResourceManager.GetString("PlaceHolderEmail", resourceCulture);
            }
        }
        
        internal static string PlaceHolderDOB {
            get {
                return ResourceManager.GetString("PlaceHolderDOB", resourceCulture);
            }
        }
        
        internal static string PlaceHolderPhoneNumber {
            get {
                return ResourceManager.GetString("PlaceHolderPhoneNumber", resourceCulture);
            }
        }
        
        internal static string PlaceHolderPassword {
            get {
                return ResourceManager.GetString("PlaceHolderPassword", resourceCulture);
            }
        }
        
        internal static string AgreeTermsAndConditions1Text {
            get {
                return ResourceManager.GetString("AgreeTermsAndConditions1Text", resourceCulture);
            }
        }
        
        internal static string AgreeTermsAndConditions2Text {
            get {
                return ResourceManager.GetString("AgreeTermsAndConditions2Text", resourceCulture);
            }
        }
        
        internal static string AgreeTermsAndConditions3Text {
            get {
                return ResourceManager.GetString("AgreeTermsAndConditions3Text", resourceCulture);
            }
        }
        
        internal static string OTPTitleText {
            get {
                return ResourceManager.GetString("OTPTitleText", resourceCulture);
            }
        }
        
        internal static string HavintRecievedCodeText {
            get {
                return ResourceManager.GetString("HavintRecievedCodeText", resourceCulture);
            }
        }
        
        internal static string ResentCodeText {
            get {
                return ResourceManager.GetString("ResentCodeText", resourceCulture);
            }
        }
        
        internal static string BackText {
            get {
                return ResourceManager.GetString("BackText", resourceCulture);
            }
        }
        
        internal static string ForgotPasswordTitleText {
            get {
                return ResourceManager.GetString("ForgotPasswordTitleText", resourceCulture);
            }
        }
        
        internal static string SendText {
            get {
                return ResourceManager.GetString("SendText", resourceCulture);
            }
        }
        
        internal static string AccuracyIn {
            get {
                return ResourceManager.GetString("AccuracyIn", resourceCulture);
            }
        }
        
        internal static string Baseball {
            get {
                return ResourceManager.GetString("Baseball", resourceCulture);
            }
        }
        
        internal static string Basketball {
            get {
                return ResourceManager.GetString("Basketball", resourceCulture);
            }
        }
        
        internal static string Football {
            get {
                return ResourceManager.GetString("Football", resourceCulture);
            }
        }
        
        internal static string Hocky {
            get {
                return ResourceManager.GetString("Hocky", resourceCulture);
            }
        }
        
        internal static string MMA {
            get {
                return ResourceManager.GetString("MMA", resourceCulture);
            }
        }
        
        internal static string LastPredictions {
            get {
                return ResourceManager.GetString("LastPredictions", resourceCulture);
            }
        }
        
        internal static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        internal static string Avg {
            get {
                return ResourceManager.GetString("Avg", resourceCulture);
            }
        }
        
        internal static string Bad {
            get {
                return ResourceManager.GetString("Bad", resourceCulture);
            }
        }
        
        internal static string PickBy {
            get {
                return ResourceManager.GetString("PickBy", resourceCulture);
            }
        }
        
        internal static string Vs {
            get {
                return ResourceManager.GetString("Vs", resourceCulture);
            }
        }
        
        internal static string BuyThisPick {
            get {
                return ResourceManager.GetString("BuyThisPick", resourceCulture);
            }
        }
        
        internal static string Unfollow {
            get {
                return ResourceManager.GetString("Unfollow", resourceCulture);
            }
        }
        
        internal static string HidePost {
            get {
                return ResourceManager.GetString("HidePost", resourceCulture);
            }
        }
        
        internal static string SharePost {
            get {
                return ResourceManager.GetString("SharePost", resourceCulture);
            }
        }
        
        internal static string ReportPost {
            get {
                return ResourceManager.GetString("ReportPost", resourceCulture);
            }
        }
        
        internal static string LifetimePredictions {
            get {
                return ResourceManager.GetString("LifetimePredictions", resourceCulture);
            }
        }
        
        internal static string Last15Predictions {
            get {
                return ResourceManager.GetString("Last15Predictions", resourceCulture);
            }
        }
        
        internal static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        internal static string Picks {
            get {
                return ResourceManager.GetString("Picks", resourceCulture);
            }
        }
        
        internal static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        internal static string Following {
            get {
                return ResourceManager.GetString("Following", resourceCulture);
            }
        }
        
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        internal static string EnterCommentPlaceHolder {
            get {
                return ResourceManager.GetString("EnterCommentPlaceHolder", resourceCulture);
            }
        }
        
        internal static string PostYourPick {
            get {
                return ResourceManager.GetString("PostYourPick", resourceCulture);
            }
        }
        
        internal static string NextText {
            get {
                return ResourceManager.GetString("NextText", resourceCulture);
            }
        }
        
        internal static string SelectYourSpot {
            get {
                return ResourceManager.GetString("SelectYourSpot", resourceCulture);
            }
        }
        
        internal static string SelectYourLeague {
            get {
                return ResourceManager.GetString("SelectYourLeague", resourceCulture);
            }
        }
        
        internal static string NoConnectionMessage {
            get {
                return ResourceManager.GetString("NoConnectionMessage", resourceCulture);
            }
        }
        
        internal static string RemoteServerFailed {
            get {
                return ResourceManager.GetString("RemoteServerFailed", resourceCulture);
            }
        }
        
        internal static string ConfirmLogout {
            get {
                return ResourceManager.GetString("ConfirmLogout", resourceCulture);
            }
        }
        
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
    }
}
