//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tail.Common {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Tail.Common.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string OKText {
            get {
                return ResourceManager.GetString("OKText", resourceCulture);
            }
        }
        
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        internal static string SubmitText {
            get {
                return ResourceManager.GetString("SubmitText", resourceCulture);
            }
        }
        
        internal static string ContinueText {
            get {
                return ResourceManager.GetString("ContinueText", resourceCulture);
            }
        }
        
        internal static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
        
        internal static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        internal static string FreeText {
            get {
                return ResourceManager.GetString("FreeText", resourceCulture);
            }
        }
        
        internal static string PaidText {
            get {
                return ResourceManager.GetString("PaidText", resourceCulture);
            }
        }
        
        internal static string MoneyLineText {
            get {
                return ResourceManager.GetString("MoneyLineText", resourceCulture);
            }
        }
        
        internal static string SpreadText {
            get {
                return ResourceManager.GetString("SpreadText", resourceCulture);
            }
        }
        
        internal static string OverUnderText {
            get {
                return ResourceManager.GetString("OverUnderText", resourceCulture);
            }
        }
        
        internal static string PurchasedText {
            get {
                return ResourceManager.GetString("PurchasedText", resourceCulture);
            }
        }
        
        internal static string SinglePurchasedText {
            get {
                return ResourceManager.GetString("SinglePurchasedText", resourceCulture);
            }
        }
        
        internal static string FacebookText {
            get {
                return ResourceManager.GetString("FacebookText", resourceCulture);
            }
        }
        
        internal static string AppleText {
            get {
                return ResourceManager.GetString("AppleText", resourceCulture);
            }
        }
        
        internal static string GoogleText {
            get {
                return ResourceManager.GetString("GoogleText", resourceCulture);
            }
        }
        
        internal static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        internal static string ForgotPasswordText {
            get {
                return ResourceManager.GetString("ForgotPasswordText", resourceCulture);
            }
        }
        
        internal static string RememberMeText {
            get {
                return ResourceManager.GetString("RememberMeText", resourceCulture);
            }
        }
        
        internal static string DontHaveAccountText {
            get {
                return ResourceManager.GetString("DontHaveAccountText", resourceCulture);
            }
        }
        
        internal static string SignUpText {
            get {
                return ResourceManager.GetString("SignUpText", resourceCulture);
            }
        }
        
        internal static string OrText {
            get {
                return ResourceManager.GetString("OrText", resourceCulture);
            }
        }
        
        internal static string SkipText {
            get {
                return ResourceManager.GetString("SkipText", resourceCulture);
            }
        }
        
        internal static string FacebookSignUpText {
            get {
                return ResourceManager.GetString("FacebookSignUpText", resourceCulture);
            }
        }
        
        internal static string AppleSignUpText {
            get {
                return ResourceManager.GetString("AppleSignUpText", resourceCulture);
            }
        }
        
        internal static string GoogleSignUpText {
            get {
                return ResourceManager.GetString("GoogleSignUpText", resourceCulture);
            }
        }
        
        internal static string SignUpTitleText {
            get {
                return ResourceManager.GetString("SignUpTitleText", resourceCulture);
            }
        }
        
        internal static string EmailSignUpText {
            get {
                return ResourceManager.GetString("EmailSignUpText", resourceCulture);
            }
        }
        
        internal static string AlreadyHaveAccountText {
            get {
                return ResourceManager.GetString("AlreadyHaveAccountText", resourceCulture);
            }
        }
        
        internal static string CreateAccountText {
            get {
                return ResourceManager.GetString("CreateAccountText", resourceCulture);
            }
        }
        
        internal static string CreateAccountButtonText {
            get {
                return ResourceManager.GetString("CreateAccountButtonText", resourceCulture);
            }
        }
        
        internal static string PlaceHolderName {
            get {
                return ResourceManager.GetString("PlaceHolderName", resourceCulture);
            }
        }
        
        internal static string PlaceHolderEmail {
            get {
                return ResourceManager.GetString("PlaceHolderEmail", resourceCulture);
            }
        }
        
        internal static string PlaceHolderDOB {
            get {
                return ResourceManager.GetString("PlaceHolderDOB", resourceCulture);
            }
        }
        
        internal static string PlaceHolderPhoneNumber {
            get {
                return ResourceManager.GetString("PlaceHolderPhoneNumber", resourceCulture);
            }
        }
        
        internal static string PlaceHolderPassword {
            get {
                return ResourceManager.GetString("PlaceHolderPassword", resourceCulture);
            }
        }
        
        internal static string AgreeTermsAndConditions1Text {
            get {
                return ResourceManager.GetString("AgreeTermsAndConditions1Text", resourceCulture);
            }
        }
        
        internal static string AgreeTermsAndConditions2Text {
            get {
                return ResourceManager.GetString("AgreeTermsAndConditions2Text", resourceCulture);
            }
        }
        
        internal static string AgreeTermsAndConditions3Text {
            get {
                return ResourceManager.GetString("AgreeTermsAndConditions3Text", resourceCulture);
            }
        }
        
        internal static string OTPTitleText {
            get {
                return ResourceManager.GetString("OTPTitleText", resourceCulture);
            }
        }
        
        internal static string HavintRecievedCodeText {
            get {
                return ResourceManager.GetString("HavintRecievedCodeText", resourceCulture);
            }
        }
        
        internal static string OTPWillExpireText {
            get {
                return ResourceManager.GetString("OTPWillExpireText", resourceCulture);
            }
        }
        
        internal static string OTPExpiredText {
            get {
                return ResourceManager.GetString("OTPExpiredText", resourceCulture);
            }
        }
        
        internal static string ResentCodeText {
            get {
                return ResourceManager.GetString("ResentCodeText", resourceCulture);
            }
        }
        
        internal static string BackText {
            get {
                return ResourceManager.GetString("BackText", resourceCulture);
            }
        }
        
        internal static string ForgotPasswordTitleText {
            get {
                return ResourceManager.GetString("ForgotPasswordTitleText", resourceCulture);
            }
        }
        
        internal static string SendText {
            get {
                return ResourceManager.GetString("SendText", resourceCulture);
            }
        }
        
        internal static string SelectInterestTitleText {
            get {
                return ResourceManager.GetString("SelectInterestTitleText", resourceCulture);
            }
        }
        
        internal static string SelectInterestAlertMessage {
            get {
                return ResourceManager.GetString("SelectInterestAlertMessage", resourceCulture);
            }
        }
        
        internal static string NextText {
            get {
                return ResourceManager.GetString("NextText", resourceCulture);
            }
        }
        
        internal static string PostSomethingText {
            get {
                return ResourceManager.GetString("PostSomethingText", resourceCulture);
            }
        }
        
        internal static string PostYourPickText {
            get {
                return ResourceManager.GetString("PostYourPickText", resourceCulture);
            }
        }
        
        internal static string MenuText {
            get {
                return ResourceManager.GetString("MenuText", resourceCulture);
            }
        }
        
        internal static string CreateAPostText {
            get {
                return ResourceManager.GetString("CreateAPostText", resourceCulture);
            }
        }
        
        internal static string CameraPermmission {
            get {
                return ResourceManager.GetString("CameraPermmission", resourceCulture);
            }
        }
        
        internal static string MicroPhonePermmission {
            get {
                return ResourceManager.GetString("MicroPhonePermmission", resourceCulture);
            }
        }
        
        internal static string GalleryPermmission {
            get {
                return ResourceManager.GetString("GalleryPermmission", resourceCulture);
            }
        }
        
        internal static string EnableFromSettings {
            get {
                return ResourceManager.GetString("EnableFromSettings", resourceCulture);
            }
        }
        
        internal static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        internal static string PostAPickText {
            get {
                return ResourceManager.GetString("PostAPickText", resourceCulture);
            }
        }
        
        internal static string CreatePostAlertText {
            get {
                return ResourceManager.GetString("CreatePostAlertText", resourceCulture);
            }
        }
        
        internal static string ConfirmPickPurchaceText {
            get {
                return ResourceManager.GetString("ConfirmPickPurchaceText", resourceCulture);
            }
        }
        
        internal static string PayUsingText {
            get {
                return ResourceManager.GetString("PayUsingText", resourceCulture);
            }
        }
        
        internal static string TapToChangeText {
            get {
                return ResourceManager.GetString("TapToChangeText", resourceCulture);
            }
        }
        
        internal static string NotEnoughCoinsText {
            get {
                return ResourceManager.GetString("NotEnoughCoinsText", resourceCulture);
            }
        }
        
        internal static string TailWalletText {
            get {
                return ResourceManager.GetString("TailWalletText", resourceCulture);
            }
        }
        
        internal static string PaymentMethodsText {
            get {
                return ResourceManager.GetString("PaymentMethodsText", resourceCulture);
            }
        }
        
        internal static string ActiveText {
            get {
                return ResourceManager.GetString("ActiveText", resourceCulture);
            }
        }
        
        internal static string ActivateNowText {
            get {
                return ResourceManager.GetString("ActivateNowText", resourceCulture);
            }
        }
        
        internal static string AccountDetailsText {
            get {
                return ResourceManager.GetString("AccountDetailsText", resourceCulture);
            }
        }
        
        internal static string MyPurchasesText {
            get {
                return ResourceManager.GetString("MyPurchasesText", resourceCulture);
            }
        }
        
        internal static string SavedCardsText {
            get {
                return ResourceManager.GetString("SavedCardsText", resourceCulture);
            }
        }
        
        internal static string AddNewCardText {
            get {
                return ResourceManager.GetString("AddNewCardText", resourceCulture);
            }
        }
        
        internal static string AccountHolderNameText {
            get {
                return ResourceManager.GetString("AccountHolderNameText", resourceCulture);
            }
        }
        
        internal static string EnterYourNameText {
            get {
                return ResourceManager.GetString("EnterYourNameText", resourceCulture);
            }
        }
        
        internal static string CardNumberText {
            get {
                return ResourceManager.GetString("CardNumberText", resourceCulture);
            }
        }
        
        internal static string ExpiryDateText {
            get {
                return ResourceManager.GetString("ExpiryDateText", resourceCulture);
            }
        }
        
        internal static string CVVText {
            get {
                return ResourceManager.GetString("CVVText", resourceCulture);
            }
        }
        
        internal static string AddAccountDetailsText {
            get {
                return ResourceManager.GetString("AddAccountDetailsText", resourceCulture);
            }
        }
        
        internal static string RoutingNumberText {
            get {
                return ResourceManager.GetString("RoutingNumberText", resourceCulture);
            }
        }
        
        internal static string EnterRoutingNumberText {
            get {
                return ResourceManager.GetString("EnterRoutingNumberText", resourceCulture);
            }
        }
        
        internal static string AccountNumberText {
            get {
                return ResourceManager.GetString("AccountNumberText", resourceCulture);
            }
        }
        
        internal static string EnterAccountNumberText {
            get {
                return ResourceManager.GetString("EnterAccountNumberText", resourceCulture);
            }
        }
        
        internal static string PaymentsText {
            get {
                return ResourceManager.GetString("PaymentsText", resourceCulture);
            }
        }
        
        internal static string SummaryText {
            get {
                return ResourceManager.GetString("SummaryText", resourceCulture);
            }
        }
        
        internal static string CoinBalanceText {
            get {
                return ResourceManager.GetString("CoinBalanceText", resourceCulture);
            }
        }
        
        internal static string EarningsBalanceText {
            get {
                return ResourceManager.GetString("EarningsBalanceText", resourceCulture);
            }
        }
        
        internal static string TotalsBalanceText {
            get {
                return ResourceManager.GetString("TotalsBalanceText", resourceCulture);
            }
        }
        
        internal static string CoinsText {
            get {
                return ResourceManager.GetString("CoinsText", resourceCulture);
            }
        }
        
        internal static string AddCoinsText {
            get {
                return ResourceManager.GetString("AddCoinsText", resourceCulture);
            }
        }
        
        internal static string PayNowText {
            get {
                return ResourceManager.GetString("PayNowText", resourceCulture);
            }
        }
        
        internal static string BuyText {
            get {
                return ResourceManager.GetString("BuyText", resourceCulture);
            }
        }
        
        internal static string TailCoinsText {
            get {
                return ResourceManager.GetString("TailCoinsText", resourceCulture);
            }
        }
        
        internal static string AvailableBalanceText {
            get {
                return ResourceManager.GetString("AvailableBalanceText", resourceCulture);
            }
        }
        
        internal static string TransactionHistoryText {
            get {
                return ResourceManager.GetString("TransactionHistoryText", resourceCulture);
            }
        }
        
        internal static string Coins10Text {
            get {
                return ResourceManager.GetString("Coins10Text", resourceCulture);
            }
        }
        
        internal static string Coins20Text {
            get {
                return ResourceManager.GetString("Coins20Text", resourceCulture);
            }
        }
        
        internal static string Coins30Text {
            get {
                return ResourceManager.GetString("Coins30Text", resourceCulture);
            }
        }
        
        internal static string Coins40Text {
            get {
                return ResourceManager.GetString("Coins40Text", resourceCulture);
            }
        }
        
        internal static string Coins50Text {
            get {
                return ResourceManager.GetString("Coins50Text", resourceCulture);
            }
        }
        
        internal static string TransactionsText {
            get {
                return ResourceManager.GetString("TransactionsText", resourceCulture);
            }
        }
        
        internal static string AchivedPercentageText {
            get {
                return ResourceManager.GetString("AchivedPercentageText", resourceCulture);
            }
        }
        
        internal static string EarningsSummaryText {
            get {
                return ResourceManager.GetString("EarningsSummaryText", resourceCulture);
            }
        }
        
        internal static string YourEarningsText {
            get {
                return ResourceManager.GetString("YourEarningsText", resourceCulture);
            }
        }
        
        internal static string ClickToChangeText {
            get {
                return ResourceManager.GetString("ClickToChangeText", resourceCulture);
            }
        }
        
        internal static string PayoutDescText {
            get {
                return ResourceManager.GetString("PayoutDescText", resourceCulture);
            }
        }
        
        internal static string PayText {
            get {
                return ResourceManager.GetString("PayText", resourceCulture);
            }
        }
        
        internal static string PayCoinsText {
            get {
                return ResourceManager.GetString("PayCoinsText", resourceCulture);
            }
        }
        
        internal static string UploadFailedText {
            get {
                return ResourceManager.GetString("UploadFailedText", resourceCulture);
            }
        }
        
        internal static string AttchmentLimitAlertText {
            get {
                return ResourceManager.GetString("AttchmentLimitAlertText", resourceCulture);
            }
        }
        
        internal static string UPloadSizeExeedsAlertText {
            get {
                return ResourceManager.GetString("UPloadSizeExeedsAlertText", resourceCulture);
            }
        }
        
        internal static string AccuracyIn {
            get {
                return ResourceManager.GetString("AccuracyIn", resourceCulture);
            }
        }
        
        internal static string Baseball {
            get {
                return ResourceManager.GetString("Baseball", resourceCulture);
            }
        }
        
        internal static string Basketball {
            get {
                return ResourceManager.GetString("Basketball", resourceCulture);
            }
        }
        
        internal static string Football {
            get {
                return ResourceManager.GetString("Football", resourceCulture);
            }
        }
        
        internal static string Hocky {
            get {
                return ResourceManager.GetString("Hocky", resourceCulture);
            }
        }
        
        internal static string MMA {
            get {
                return ResourceManager.GetString("MMA", resourceCulture);
            }
        }
        
        internal static string LastPredictions {
            get {
                return ResourceManager.GetString("LastPredictions", resourceCulture);
            }
        }
        
        internal static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        internal static string Avg {
            get {
                return ResourceManager.GetString("Avg", resourceCulture);
            }
        }
        
        internal static string Bad {
            get {
                return ResourceManager.GetString("Bad", resourceCulture);
            }
        }
        
        internal static string PickBy {
            get {
                return ResourceManager.GetString("PickBy", resourceCulture);
            }
        }
        
        internal static string Vs {
            get {
                return ResourceManager.GetString("Vs", resourceCulture);
            }
        }
        
        internal static string BuyThisPick {
            get {
                return ResourceManager.GetString("BuyThisPick", resourceCulture);
            }
        }
        
        internal static string Unfollow {
            get {
                return ResourceManager.GetString("Unfollow", resourceCulture);
            }
        }
        
        internal static string HidePost {
            get {
                return ResourceManager.GetString("HidePost", resourceCulture);
            }
        }
        
        internal static string SharePost {
            get {
                return ResourceManager.GetString("SharePost", resourceCulture);
            }
        }
        
        internal static string ReportedPost {
            get {
                return ResourceManager.GetString("ReportedPost", resourceCulture);
            }
        }
        
        internal static string ReportPost {
            get {
                return ResourceManager.GetString("ReportPost", resourceCulture);
            }
        }
        
        internal static string LifetimePredictions {
            get {
                return ResourceManager.GetString("LifetimePredictions", resourceCulture);
            }
        }
        
        internal static string Last15Predictions {
            get {
                return ResourceManager.GetString("Last15Predictions", resourceCulture);
            }
        }
        
        internal static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        internal static string Picks {
            get {
                return ResourceManager.GetString("Picks", resourceCulture);
            }
        }
        
        internal static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        internal static string Following {
            get {
                return ResourceManager.GetString("Following", resourceCulture);
            }
        }
        
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        internal static string EnterCommentPlaceHolder {
            get {
                return ResourceManager.GetString("EnterCommentPlaceHolder", resourceCulture);
            }
        }
        
        internal static string PostYourPick {
            get {
                return ResourceManager.GetString("PostYourPick", resourceCulture);
            }
        }
        
        internal static string SelectYourSpot {
            get {
                return ResourceManager.GetString("SelectYourSpot", resourceCulture);
            }
        }
        
        internal static string SelectYourLeague {
            get {
                return ResourceManager.GetString("SelectYourLeague", resourceCulture);
            }
        }
        
        internal static string SelectTheGame {
            get {
                return ResourceManager.GetString("SelectTheGame", resourceCulture);
            }
        }
        
        internal static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        internal static string FollowersCount {
            get {
                return ResourceManager.GetString("FollowersCount", resourceCulture);
            }
        }
        
        internal static string FollowingCount {
            get {
                return ResourceManager.GetString("FollowingCount", resourceCulture);
            }
        }
        
        internal static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        internal static string PostNow {
            get {
                return ResourceManager.GetString("PostNow", resourceCulture);
            }
        }
        
        internal static string TapOnEditText {
            get {
                return ResourceManager.GetString("TapOnEditText", resourceCulture);
            }
        }
        
        internal static string ToEdit {
            get {
                return ResourceManager.GetString("ToEdit", resourceCulture);
            }
        }
        
        internal static string PickFee {
            get {
                return ResourceManager.GetString("PickFee", resourceCulture);
            }
        }
        
        internal static string FollowingText {
            get {
                return ResourceManager.GetString("FollowingText", resourceCulture);
            }
        }
        
        internal static string EditProfileText {
            get {
                return ResourceManager.GetString("EditProfileText", resourceCulture);
            }
        }
        
        internal static string PaymentMethods {
            get {
                return ResourceManager.GetString("PaymentMethods", resourceCulture);
            }
        }
        
        internal static string AccountDetails {
            get {
                return ResourceManager.GetString("AccountDetails", resourceCulture);
            }
        }
        
        internal static string FollowRecommendedText {
            get {
                return ResourceManager.GetString("FollowRecommendedText", resourceCulture);
            }
        }
        
        internal static string Purchases {
            get {
                return ResourceManager.GetString("Purchases", resourceCulture);
            }
        }
        
        internal static string PriceHintText {
            get {
                return ResourceManager.GetString("PriceHintText", resourceCulture);
            }
        }
        
        internal static string WageringHintText {
            get {
                return ResourceManager.GetString("WageringHintText", resourceCulture);
            }
        }
        
        internal static string WageringUnitText {
            get {
                return ResourceManager.GetString("WageringUnitText", resourceCulture);
            }
        }
        
        internal static string SelectText {
            get {
                return ResourceManager.GetString("SelectText", resourceCulture);
            }
        }
        
        internal static string SelectedText {
            get {
                return ResourceManager.GetString("SelectedText", resourceCulture);
            }
        }
        
        internal static string DeletePostText {
            get {
                return ResourceManager.GetString("DeletePostText", resourceCulture);
            }
        }
        
        internal static string DeletePickText {
            get {
                return ResourceManager.GetString("DeletePickText", resourceCulture);
            }
        }
        
        internal static string WillWinText {
            get {
                return ResourceManager.GetString("WillWinText", resourceCulture);
            }
        }
        
        internal static string HasWonText {
            get {
                return ResourceManager.GetString("HasWonText", resourceCulture);
            }
        }
        
        internal static string SelectYourIssue {
            get {
                return ResourceManager.GetString("SelectYourIssue", resourceCulture);
            }
        }
        
        internal static string BetTypeText {
            get {
                return ResourceManager.GetString("BetTypeText", resourceCulture);
            }
        }
        
        internal static string SelectBetTypeText {
            get {
                return ResourceManager.GetString("SelectBetTypeText", resourceCulture);
            }
        }
        
        internal static string ElaborateIssue {
            get {
                return ResourceManager.GetString("ElaborateIssue", resourceCulture);
            }
        }
        
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        internal static string AboutUsText1 {
            get {
                return ResourceManager.GetString("AboutUsText1", resourceCulture);
            }
        }
        
        internal static string AboutUsText2 {
            get {
                return ResourceManager.GetString("AboutUsText2", resourceCulture);
            }
        }
        
        internal static string ContactText {
            get {
                return ResourceManager.GetString("ContactText", resourceCulture);
            }
        }
        
        internal static string SendUsQuery {
            get {
                return ResourceManager.GetString("SendUsQuery", resourceCulture);
            }
        }
        
        internal static string QuerySubject {
            get {
                return ResourceManager.GetString("QuerySubject", resourceCulture);
            }
        }
        
        internal static string QuerySubjectValidation {
            get {
                return ResourceManager.GetString("QuerySubjectValidation", resourceCulture);
            }
        }
        
        internal static string QueryContent {
            get {
                return ResourceManager.GetString("QueryContent", resourceCulture);
            }
        }
        
        internal static string QueryContentValidation {
            get {
                return ResourceManager.GetString("QueryContentValidation", resourceCulture);
            }
        }
        
        internal static string UploadScreenshot {
            get {
                return ResourceManager.GetString("UploadScreenshot", resourceCulture);
            }
        }
        
        internal static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        internal static string FailedText {
            get {
                return ResourceManager.GetString("FailedText", resourceCulture);
            }
        }
        
        internal static string RefundText {
            get {
                return ResourceManager.GetString("RefundText", resourceCulture);
            }
        }
        
        internal static string NotificationText {
            get {
                return ResourceManager.GetString("NotificationText", resourceCulture);
            }
        }
        
        internal static string SearchPlaceHolder {
            get {
                return ResourceManager.GetString("SearchPlaceHolder", resourceCulture);
            }
        }
        
        internal static string TrendingInPeople {
            get {
                return ResourceManager.GetString("TrendingInPeople", resourceCulture);
            }
        }
        
        internal static string TrendingInPicks {
            get {
                return ResourceManager.GetString("TrendingInPicks", resourceCulture);
            }
        }
        
        internal static string TrendingInPosts {
            get {
                return ResourceManager.GetString("TrendingInPosts", resourceCulture);
            }
        }
        
        internal static string SearchResultInPosts {
            get {
                return ResourceManager.GetString("SearchResultInPosts", resourceCulture);
            }
        }
        
        internal static string SearchResultInPicks {
            get {
                return ResourceManager.GetString("SearchResultInPicks", resourceCulture);
            }
        }
        
        internal static string SearchResultInPeople {
            get {
                return ResourceManager.GetString("SearchResultInPeople", resourceCulture);
            }
        }
        
        internal static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        internal static string PostText {
            get {
                return ResourceManager.GetString("PostText", resourceCulture);
            }
        }
        
        internal static string YouBoughtText {
            get {
                return ResourceManager.GetString("YouBoughtText", resourceCulture);
            }
        }
        
        internal static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        internal static string NoConnectionMessage {
            get {
                return ResourceManager.GetString("NoConnectionMessage", resourceCulture);
            }
        }
        
        internal static string RemoteServerFailed {
            get {
                return ResourceManager.GetString("RemoteServerFailed", resourceCulture);
            }
        }
        
        internal static string ConfirmLogout {
            get {
                return ResourceManager.GetString("ConfirmLogout", resourceCulture);
            }
        }
        
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        internal static string SelectYourSpotInfo {
            get {
                return ResourceManager.GetString("SelectYourSpotInfo", resourceCulture);
            }
        }
        
        internal static string SelectYourLeagueInfo {
            get {
                return ResourceManager.GetString("SelectYourLeagueInfo", resourceCulture);
            }
        }
        
        internal static string SelectYourTeamText {
            get {
                return ResourceManager.GetString("SelectYourTeamText", resourceCulture);
            }
        }
        
        internal static string GameInfo {
            get {
                return ResourceManager.GetString("GameInfo", resourceCulture);
            }
        }
        
        internal static string GameSelectionWarning {
            get {
                return ResourceManager.GetString("GameSelectionWarning", resourceCulture);
            }
        }
        
        internal static string WriteYourPost {
            get {
                return ResourceManager.GetString("WriteYourPost", resourceCulture);
            }
        }
        
        internal static string AppExitMessage {
            get {
                return ResourceManager.GetString("AppExitMessage", resourceCulture);
            }
        }
        
        internal static string OTPVerificationText {
            get {
                return ResourceManager.GetString("OTPVerificationText", resourceCulture);
            }
        }
        
        internal static string UpdateDetails {
            get {
                return ResourceManager.GetString("UpdateDetails", resourceCulture);
            }
        }
        
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        internal static string RemoveAccount {
            get {
                return ResourceManager.GetString("RemoveAccount", resourceCulture);
            }
        }
        
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        internal static string EnterCurrentPassword {
            get {
                return ResourceManager.GetString("EnterCurrentPassword", resourceCulture);
            }
        }
        
        internal static string EnterNewPassword {
            get {
                return ResourceManager.GetString("EnterNewPassword", resourceCulture);
            }
        }
        
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        internal static string AboutMeText {
            get {
                return ResourceManager.GetString("AboutMeText", resourceCulture);
            }
        }
        
        internal static string DiscoverPeople {
            get {
                return ResourceManager.GetString("DiscoverPeople", resourceCulture);
            }
        }
        
        internal static string EmailNotifications {
            get {
                return ResourceManager.GetString("EmailNotifications", resourceCulture);
            }
        }
        
        internal static string AppNotifications {
            get {
                return ResourceManager.GetString("AppNotifications", resourceCulture);
            }
        }
        
        internal static string LikeDislike {
            get {
                return ResourceManager.GetString("LikeDislike", resourceCulture);
            }
        }
        
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        internal static string NewFollowers {
            get {
                return ResourceManager.GetString("NewFollowers", resourceCulture);
            }
        }
        
        internal static string ReportAProblem {
            get {
                return ResourceManager.GetString("ReportAProblem", resourceCulture);
            }
        }
        
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        internal static string RateUs {
            get {
                return ResourceManager.GetString("RateUs", resourceCulture);
            }
        }
        
        internal static string ClearText {
            get {
                return ResourceManager.GetString("ClearText", resourceCulture);
            }
        }
        
        internal static string ConfirmClear {
            get {
                return ResourceManager.GetString("ConfirmClear", resourceCulture);
            }
        }
        
        internal static string NotificationInfo {
            get {
                return ResourceManager.GetString("NotificationInfo", resourceCulture);
            }
        }
        
        internal static string FilterSports {
            get {
                return ResourceManager.GetString("FilterSports", resourceCulture);
            }
        }
        
        internal static string PicksInfo {
            get {
                return ResourceManager.GetString("PicksInfo", resourceCulture);
            }
        }
        
        internal static string PurchaseInfo {
            get {
                return ResourceManager.GetString("PurchaseInfo", resourceCulture);
            }
        }
        
        internal static string NoUsers {
            get {
                return ResourceManager.GetString("NoUsers", resourceCulture);
            }
        }
        
        internal static string SendUsProblem {
            get {
                return ResourceManager.GetString("SendUsProblem", resourceCulture);
            }
        }
        
        internal static string ReportText {
            get {
                return ResourceManager.GetString("ReportText", resourceCulture);
            }
        }
        
        internal static string ElaborateProblem {
            get {
                return ResourceManager.GetString("ElaborateProblem", resourceCulture);
            }
        }
        
        internal static string FilterPicks {
            get {
                return ResourceManager.GetString("FilterPicks", resourceCulture);
            }
        }
        
        internal static string PurchaseType {
            get {
                return ResourceManager.GetString("PurchaseType", resourceCulture);
            }
        }
        
        internal static string SportType {
            get {
                return ResourceManager.GetString("SportType", resourceCulture);
            }
        }
        
        internal static string ForText {
            get {
                return ResourceManager.GetString("ForText", resourceCulture);
            }
        }
        
        internal static string SharePlaceHolder {
            get {
                return ResourceManager.GetString("SharePlaceHolder", resourceCulture);
            }
        }
        
        internal static string ShareNow {
            get {
                return ResourceManager.GetString("ShareNow", resourceCulture);
            }
        }
        
        internal static string MoreOptions {
            get {
                return ResourceManager.GetString("MoreOptions", resourceCulture);
            }
        }
        
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        internal static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
        
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        internal static string ValidPassword {
            get {
                return ResourceManager.GetString("ValidPassword", resourceCulture);
            }
        }
        
        internal static string InValidPassword {
            get {
                return ResourceManager.GetString("InValidPassword", resourceCulture);
            }
        }
        
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        internal static string EnterDOB {
            get {
                return ResourceManager.GetString("EnterDOB", resourceCulture);
            }
        }
        
        internal static string EnterPhone {
            get {
                return ResourceManager.GetString("EnterPhone", resourceCulture);
            }
        }
        
        internal static string EnterCountry {
            get {
                return ResourceManager.GetString("EnterCountry", resourceCulture);
            }
        }
        
        internal static string AcceptTerms {
            get {
                return ResourceManager.GetString("AcceptTerms", resourceCulture);
            }
        }
        
        internal static string HideCaptionText {
            get {
                return ResourceManager.GetString("HideCaptionText", resourceCulture);
            }
        }
        
        internal static string CountryText {
            get {
                return ResourceManager.GetString("CountryText", resourceCulture);
            }
        }
        
        internal static string EnterValidCountry {
            get {
                return ResourceManager.GetString("EnterValidCountry", resourceCulture);
            }
        }
        
        internal static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        internal static string ChooseGallery {
            get {
                return ResourceManager.GetString("ChooseGallery", resourceCulture);
            }
        }
        
        internal static string AddPhoto {
            get {
                return ResourceManager.GetString("AddPhoto", resourceCulture);
            }
        }
        
        internal static string ConfirmRemoveAccount {
            get {
                return ResourceManager.GetString("ConfirmRemoveAccount", resourceCulture);
            }
        }
        
        internal static string VerifyPassword {
            get {
                return ResourceManager.GetString("VerifyPassword", resourceCulture);
            }
        }
        
        internal static string FaildText {
            get {
                return ResourceManager.GetString("FaildText", resourceCulture);
            }
        }
        
        internal static string PreviousComments {
            get {
                return ResourceManager.GetString("PreviousComments", resourceCulture);
            }
        }
        
        internal static string ConfirmCommentDelete {
            get {
                return ResourceManager.GetString("ConfirmCommentDelete", resourceCulture);
            }
        }
        
        internal static string HomeFeedInfo {
            get {
                return ResourceManager.GetString("HomeFeedInfo", resourceCulture);
            }
        }
        
        internal static string NoTransactionInfo {
            get {
                return ResourceManager.GetString("NoTransactionInfo", resourceCulture);
            }
        }
        
        internal static string ConfirmPostDelete {
            get {
                return ResourceManager.GetString("ConfirmPostDelete", resourceCulture);
            }
        }
        
        internal static string ProfileUpdatedMesaage {
            get {
                return ResourceManager.GetString("ProfileUpdatedMesaage", resourceCulture);
            }
        }
        
        internal static string FollowingInfo {
            get {
                return ResourceManager.GetString("FollowingInfo", resourceCulture);
            }
        }
        
        internal static string FollowingInfoOtherUser {
            get {
                return ResourceManager.GetString("FollowingInfoOtherUser", resourceCulture);
            }
        }
        
        internal static string FollowerInfo {
            get {
                return ResourceManager.GetString("FollowerInfo", resourceCulture);
            }
        }
        
        internal static string FollowerInfoOtherUser {
            get {
                return ResourceManager.GetString("FollowerInfoOtherUser", resourceCulture);
            }
        }
        
        internal static string ReportedPostAlert {
            get {
                return ResourceManager.GetString("ReportedPostAlert", resourceCulture);
            }
        }
        
        internal static string FollowStatusAlert {
            get {
                return ResourceManager.GetString("FollowStatusAlert", resourceCulture);
            }
        }
        
        internal static string UnFollowStatusAlert {
            get {
                return ResourceManager.GetString("UnFollowStatusAlert", resourceCulture);
            }
        }
        
        internal static string PrivacyPolicyText {
            get {
                return ResourceManager.GetString("PrivacyPolicyText", resourceCulture);
            }
        }
        
        internal static string FreePickButtonText {
            get {
                return ResourceManager.GetString("FreePickButtonText", resourceCulture);
            }
        }
        
        internal static string TextCoins {
            get {
                return ResourceManager.GetString("TextCoins", resourceCulture);
            }
        }
        
        internal static string OverScorePrediction {
            get {
                return ResourceManager.GetString("OverScorePrediction", resourceCulture);
            }
        }
        
        internal static string UnderScorePrediction {
            get {
                return ResourceManager.GetString("UnderScorePrediction", resourceCulture);
            }
        }
        
        internal static string SharePick {
            get {
                return ResourceManager.GetString("SharePick", resourceCulture);
            }
        }
        
        internal static string SocialMediaSharePickText {
            get {
                return ResourceManager.GetString("SocialMediaSharePickText", resourceCulture);
            }
        }
        
        internal static string SocialMediaSharePostText {
            get {
                return ResourceManager.GetString("SocialMediaSharePostText", resourceCulture);
            }
        }
        
        internal static string DownloadAppText {
            get {
                return ResourceManager.GetString("DownloadAppText", resourceCulture);
            }
        }
        
        internal static string HidePick {
            get {
                return ResourceManager.GetString("HidePick", resourceCulture);
            }
        }
        
        internal static string ReportPick {
            get {
                return ResourceManager.GetString("ReportPick", resourceCulture);
            }
        }
        
        internal static string ConfirmPickDelete {
            get {
                return ResourceManager.GetString("ConfirmPickDelete", resourceCulture);
            }
        }
        
        internal static string SelectABet {
            get {
                return ResourceManager.GetString("SelectABet", resourceCulture);
            }
        }
        
        internal static string UnlockText {
            get {
                return ResourceManager.GetString("UnlockText", resourceCulture);
            }
        }
        
        internal static string UnlockTextSingle {
            get {
                return ResourceManager.GetString("UnlockTextSingle", resourceCulture);
            }
        }
        
        internal static string BuyNowText {
            get {
                return ResourceManager.GetString("BuyNowText", resourceCulture);
            }
        }
        
        internal static string UpdateText {
            get {
                return ResourceManager.GetString("UpdateText", resourceCulture);
            }
        }
        
        internal static string UpdatePopUpTitleText {
            get {
                return ResourceManager.GetString("UpdatePopUpTitleText", resourceCulture);
            }
        }
        
        internal static string UpdatePopUpDescText {
            get {
                return ResourceManager.GetString("UpdatePopUpDescText", resourceCulture);
            }
        }
        
        internal static string MySharedsText {
            get {
                return ResourceManager.GetString("MySharedsText", resourceCulture);
            }
        }
        
        internal static string NoNotifications {
            get {
                return ResourceManager.GetString("NoNotifications", resourceCulture);
            }
        }
        
        internal static string ResultInfoText {
            get {
                return ResourceManager.GetString("ResultInfoText", resourceCulture);
            }
        }
        
        internal static string WebAddCoinsText {
            get {
                return ResourceManager.GetString("WebAddCoinsText", resourceCulture);
            }
        }
        
        internal static string FAQText {
            get {
                return ResourceManager.GetString("FAQText", resourceCulture);
            }
        }
        
        internal static string WaitingForResult {
            get {
                return ResourceManager.GetString("WaitingForResult", resourceCulture);
            }
        }
        
        internal static string GameStarted {
            get {
                return ResourceManager.GetString("GameStarted", resourceCulture);
            }
        }
        
        internal static string WonText {
            get {
                return ResourceManager.GetString("WonText", resourceCulture);
            }
        }
        
        internal static string LostText {
            get {
                return ResourceManager.GetString("LostText", resourceCulture);
            }
        }
        
        internal static string PushText {
            get {
                return ResourceManager.GetString("PushText", resourceCulture);
            }
        }
        
        internal static string ConfirmShareDelete {
            get {
                return ResourceManager.GetString("ConfirmShareDelete", resourceCulture);
            }
        }
        
        internal static string UnitText {
            get {
                return ResourceManager.GetString("UnitText", resourceCulture);
            }
        }
        
        internal static string LifeTimeUnitText {
            get {
                return ResourceManager.GetString("LifeTimeUnitText", resourceCulture);
            }
        }
        
        internal static string LastFewUnitText {
            get {
                return ResourceManager.GetString("LastFewUnitText", resourceCulture);
            }
        }
        
        internal static string SessionExpireMessage {
            get {
                return ResourceManager.GetString("SessionExpireMessage", resourceCulture);
            }
        }
        
        internal static string ContentNotAvailable {
            get {
                return ResourceManager.GetString("ContentNotAvailable", resourceCulture);
            }
        }
        
        internal static string SharedPick {
            get {
                return ResourceManager.GetString("SharedPick", resourceCulture);
            }
        }
        
        internal static string SharedPost {
            get {
                return ResourceManager.GetString("SharedPost", resourceCulture);
            }
        }
        
        internal static string AnonymousUser {
            get {
                return ResourceManager.GetString("AnonymousUser", resourceCulture);
            }
        }
    }
}
